package ec.edu.espe.Bookify.view;

import ec.edu.espe.Bookify.controller.FormsHandler;
import ec.edu.espe.Bookify.controller.InputValidation;
import ec.edu.espe.Bookify.controller.MongoDBManager;
import ec.edu.espe.Bookify.model.User;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author QUILUMBAQUIN JAIRO, DCC0-ESPE: CODEX++
 */
public class FrmDeleteUser extends javax.swing.JFrame {

    /**
     * Creates new form FrmDeleteUser
     */
    User user = new User();
    InputValidation input = new InputValidation();
    MongoDBManager bookifydb = new MongoDBManager();

    public FrmDeleteUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        Toolkit miPantalla = Toolkit.getDefaultToolkit();
        Image miIcono = miPantalla.getImage("src/Images/BookIco.png");
        setIconImage(miIcono);
        btnReturn.setOpaque(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.setBorderPainted(false);
        DeleteBtn.setEnabled(false);
        tblUserFound.setEnabled(false);
        //tblUserFound.getTableHeader().setResizingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserFound = new javax.swing.JTable();
        btnFind = new javax.swing.JButton();
        TFtoFindId = new javax.swing.JTextField();
        DeleteBtn = new javax.swing.JButton();
        lblErrorId = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUserFound.setBackground(new java.awt.Color(153, 255, 153));
        tblUserFound.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Id", "Email", "Phone", "Address", "Age", "Password"
            }
        ));
        tblUserFound.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblUserFound);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 800, 90));

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel1.add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        TFtoFindId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFtoFindIdKeyPressed(evt);
            }
        });
        jPanel1.add(TFtoFindId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 240, -1));

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        lblErrorId.setText("_");
        jPanel1.add(lblErrorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Return.png"))); // NOI18N
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        if (!TFtoFindId.getText().isBlank()) {
            findUser();
        } else {
            JOptionPane.showMessageDialog(this, "The Field Id is Empty,please fill it with a valid Id");
        }

    }//GEN-LAST:event_btnFindActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        if (!TFtoFindId.getText().isBlank()) {
            DeleteUserBtn();
        } else {
            JOptionPane.showMessageDialog(this, "The Field Id is Empty,please fill it with a valid Id");
        }
        
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void TFtoFindIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFtoFindIdKeyPressed
        input.NumberValidation(TFtoFindId, evt, lblErrorId, 9);
    }//GEN-LAST:event_TFtoFindIdKeyPressed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        FrmUser1 frmUser1 = new FrmUser1();
        frmUser1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDeleteUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDeleteUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField TFtoFindId;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReturn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorId;
    private javax.swing.JTable tblUserFound;
    // End of variables declaration//GEN-END:variables

    public User findUser() {

        User userFound;
        FormsHandler frms;

        frms = new FormsHandler();
        userFound = (User) frms.findBookifyObject(new User(), "Users", "id", Integer.parseInt(TFtoFindId.getText()));

        if (userFound != null) {
            JOptionPane.showMessageDialog(this, "User Found");
            setUserFoundTotable(userFound);
            DeleteBtn.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(this, "User doesnt exist");
            DeleteBtn.setEnabled(false);
            ClearTable();
        }

        return userFound;

    }

    public void DeleteUserBtn() {
        User userToDelete;
        userToDelete = findUser();
        
        if (userToDelete!=null) {
            bookifydb.DelteBookifyObject("Users", "id", Integer.parseInt(TFtoFindId.getText()));
            DeleteBtn.setEnabled(false);
            ClearTable();
             TFtoFindId.setText("");
        } 
    }

    public void setUserFoundTotable(User userfound) {
        FormsHandler setTable;
        ArrayList<User> userToSet;
        DefaultTableModel model;
        
        setTable = new FormsHandler();
        userToSet= new ArrayList<>();
        
        if (userfound!=null) {
            userToSet.add(userfound);
            model = setTable.SetDatatoTables(user.atributeNames(), userToSet);
            tblUserFound.setModel(model);
            tblUserFound.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblUserFound.getColumnModel().getColumn(2).setPreferredWidth(150);
        } 
        
        
            
    }
    
    public void ClearTable(){
    
        DefaultTableModel model;
        model=new DefaultTableModel(null,user.atributeNames());
        tblUserFound.setModel(model);
    
    }
    
}
