package ec.edu.espe.Bookify.view;

import ec.edu.espe.Bookify.view.FrmUserMain;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Raul Silva, DCCO-ESPE, CODEX++
 */
public class FrmRentBook extends javax.swing.JFrame {

    /**
     * Creates new form FrmRentBook
     */
    public FrmRentBook() {
        this.setLocationRelativeTo(null);
        initComponents();
        this.setLocationRelativeTo(null);
        Toolkit miPantalla = Toolkit.getDefaultToolkit();
        Image miIcono = miPantalla.getImage("src/Images/BookIco.png");
        setIconImage(miIcono);
        setTitle("Borrow book");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBook = new javax.swing.JLabel();
        btnRentBook = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BookScott.jpg"))); // NOI18N
        getContentPane().add(jLabelBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        btnRentBook.setText("Rent Book");
        btnRentBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRentBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnRentBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Fondo 01.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRentBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRentBookActionPerformed
        JOptionPane.showMessageDialog(this,"Successfully rented book");
    }//GEN-LAST:event_btnRentBookActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        FrmUserMain frmUserMain = new FrmUserMain();
        frmUserMain.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRentBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRentBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRentBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRentBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRentBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRentBook;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabelBook;
    private javax.swing.JLabel jLabelFondo;
    // End of variables declaration//GEN-END:variables
}
