/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.Bookify.view;

import ec.edu.espe.Bookify.controller.FormsHandler;
import ec.edu.espe.Bookify.controller.InputValidation;
import ec.edu.espe.Bookify.controller.MongoDBManager;
import ec.edu.espe.Bookify.model.User;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author QUILUMBAQUIN JAIRO, DCC0-ESPE: CODEX++
 */
public class FrmUpdateUser extends javax.swing.JFrame {

    User user = new User();
    InputValidation input = new InputValidation();
    MongoDBManager bookifydb = new MongoDBManager();

    public FrmUpdateUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        Toolkit miPantalla = Toolkit.getDefaultToolkit();
        Image miIcono = miPantalla.getImage("src/Images/BookIco.png");
        setIconImage(miIcono);
        btnReturn.setOpaque(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.setBorderPainted(false);
        cbxEmail.setVisible(false);
        loadComboBox(user.atributeNames(), cbxUpdateValue);
        loadComboBox(new String[]{"@gmail.com", "@Outlook.com", "@yahoo.com", "@hotmail.com"}, cbxEmail);
        btnUpdate.setEnabled(false);
        tblDataUpdate.setEnabled(false);
        tblDataUpdate.getTableHeader().setResizingAllowed(false);
        
        btnUpdate.setEnabled(false);
        TFToUpdatedata.setText("");
        TFToUpdatedata.setEnabled(false);
        cbxUpdateValue.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataUpdate = new javax.swing.JTable();
        cbxUpdateValue = new javax.swing.JComboBox<>();
        TFToUpdatedata = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        cbxEmail = new javax.swing.JComboBox<>();
        lblErrorUpdateFill = new javax.swing.JLabel();
        TFtofindId = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblErrorId = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDataUpdate.setBackground(new java.awt.Color(153, 255, 153));
        tblDataUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Id", "Email", "Phone", "Addres", "Age", "Password"
            }
        ));
        tblDataUpdate.setEnabled(false);
        tblDataUpdate.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblDataUpdate);
        tblDataUpdate.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 920, 50));

        cbxUpdateValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxUpdateValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUpdateValueActionPerformed(evt);
            }
        });
        jPanel1.add(cbxUpdateValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        TFToUpdatedata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFToUpdatedataKeyPressed(evt);
            }
        });
        jPanel1.add(TFToUpdatedata, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 260, -1));

        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        cbxEmail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbxEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        lblErrorUpdateFill.setText(".");
        jPanel1.add(lblErrorUpdateFill, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        TFtofindId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFtofindIdKeyPressed(evt);
            }
        });
        jPanel1.add(TFtofindId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 171, -1));

        btnFind.setText("Buscar");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        jPanel1.add(btnFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 80, -1));

        jLabel1.setText("Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 23, -1, -1));

        lblErrorId.setText("_");
        jPanel1.add(lblErrorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Return.png"))); // NOI18N
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (!TFtofindId.getText().isBlank()) {
            UpdateUserData();
            JOptionPane.showMessageDialog(this, "User updated");

        } else {
            JOptionPane.showMessageDialog(this, "The Field Id is Empty,please fill it with a valid Id");
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void TFtofindIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFtofindIdKeyPressed
        input.NumberValidation(TFtofindId, evt, lblErrorId, 9);
    }//GEN-LAST:event_TFtofindIdKeyPressed

    private void TFToUpdatedataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFToUpdatedataKeyPressed

        switch (cbxUpdateValue.getSelectedIndex()) {
            case 0 ->
                input.StringValidation(TFToUpdatedata, evt, lblErrorUpdateFill, 30);
            case 1 ->
                input.NumberValidation(TFToUpdatedata, evt, lblErrorUpdateFill, 9);
            case 2 ->
                input.StringValidation(TFToUpdatedata, evt, lblErrorUpdateFill, 30);
            case 3 ->
                input.NumberValidation(TFToUpdatedata, evt, lblErrorUpdateFill, 9);

            case 4 ->
                input.StringValidation(TFToUpdatedata, evt, lblErrorUpdateFill, 30);

            case 5 ->
                input.NumberValidation(TFToUpdatedata, evt, lblErrorUpdateFill, 9);

            case 6 ->
                input.NumberValidation(TFToUpdatedata, evt, lblErrorUpdateFill, 9);
        }

    }//GEN-LAST:event_TFToUpdatedataKeyPressed

    private void cbxUpdateValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUpdateValueActionPerformed

        if (cbxUpdateValue.getSelectedIndex() == 2) {
            cbxEmail.setVisible(true);
        } else {
            cbxEmail.setVisible(false);
        }

        if (cbxUpdateValue.getSelectedIndex() < 7) {
            TFToUpdatedata.setText("");
        }


    }//GEN-LAST:event_cbxUpdateValueActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        if (!TFtofindId.getText().isBlank()) {
            findUser();
        } else {
            JOptionPane.showMessageDialog(this, "The Field Id is Empty,please fill it with a valid Id");
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        FrmUser1 frmUser1 = new FrmUser1();
        frmUser1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUpdateUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUpdateUser().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFToUpdatedata;
    private javax.swing.JTextField TFtofindId;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxEmail;
    private javax.swing.JComboBox<String> cbxUpdateValue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorId;
    private javax.swing.JLabel lblErrorUpdateFill;
    private javax.swing.JTable tblDataUpdate;
    // End of variables declaration//GEN-END:variables

    public void UpdateUserData() {

        String atribute;
        String idtofind;
        String toChange;

        atribute = cbxUpdateValue.getSelectedItem().toString().toLowerCase();
        idtofind = TFtofindId.getText();
        toChange = TFToUpdatedata.getText();

        switch (cbxUpdateValue.getSelectedIndex()) {

            case 0,4 ->
                bookifydb.UpdateBookifyObject("Users", "id", Integer.parseInt(idtofind), atribute, toChange);
            case 1,3,5,6 ->
                bookifydb.UpdateBookifyObject("Users", "id", Integer.parseInt(idtofind), atribute, Integer.parseInt(toChange));
            case 2 ->
                bookifydb.UpdateBookifyObject("Users", "id", Integer.parseInt(idtofind), atribute, toChange + cbxEmail.getSelectedItem());

        }

        findUser();
        TFtofindId.setText("");

    }

    public void loadComboBox(String[] datacmbbox, JComboBox<String> cbxToSet) {

        DefaultComboBoxModel cmbbox;
        cmbbox = new DefaultComboBoxModel();

        for (String ar : datacmbbox) {
            cmbbox.addElement(ar);
        }

        cbxToSet.setModel(cmbbox);

    }

    public User findUser() {

        User userFound;
        FormsHandler frms;

        frms = new FormsHandler();
        userFound = (User) frms.findBookifyObject(new User(), "Users", "id", Integer.parseInt(TFtofindId.getText()));

        if (userFound != null) {
            setUserFoundTotable(userFound);
            btnUpdate.setEnabled(true);
            TFToUpdatedata.setEnabled(true);
            cbxUpdateValue.setEnabled(true);
            
        } else {
            JOptionPane.showMessageDialog(this, "User doesnt exist");
            ClearTable();
            btnUpdate.setEnabled(false);
            TFToUpdatedata.setText("");
            TFToUpdatedata.setEnabled(false);
            cbxUpdateValue.setEnabled(false);
        }

        return userFound;

    }

    public void setUserFoundTotable(User userfound) {
        FormsHandler setTable;
        ArrayList<User> userToSet;
        DefaultTableModel model;

        setTable = new FormsHandler();
        userToSet = new ArrayList<>();

        if (userfound != null) {
            userToSet.add(userfound);
            model = setTable.SetDatatoTables(user.atributeNames(), userToSet);
            tblDataUpdate.setModel(model);
            tblDataUpdate.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblDataUpdate.getColumnModel().getColumn(2).setPreferredWidth(150);
        }

    }

    public void ClearTable() {

        DefaultTableModel model;
        model = new DefaultTableModel(null, user.atributeNames());
        tblDataUpdate.setModel(model);

    }

}
